--Q1 what is the total revenue generated by male vs. female customers?
select Gender,sum (Purchase_Amount_USD) as revenue
from customer_shopping_behavior
group by Gender

select*
from customer_shopping_behavior

--Q2 compare the average purchase amounts btw standard and express shipping
select Shipping_Type,
round (avg(Purchase_Amount_USD),2)
from customer_shopping_behavior
where Shipping_Type in ('Standard', 'Express')
group by Shipping_Type

--Q3 Do subscribed customers spend more? compare avg spend and total revenue btw subscribers and non subscribers
select Subscription_Status,
count (Customer_ID) as Total_Customers,
round (avg(Purchase_Amount_USD),2) as avg_spend,
round (sum(Purchase_Amount_USD),2) as total_revenue
from customer_shopping_behavior
group by Subscription_Status
order by total_revenue,avg_spend

--Q4 Which 5 products have the highest percentage of purchases with discounts applied?
select Item_Purchased,
round(100*sum (case when Discount_Applied = 'Yes' then 1 else 0 end)/count (*),2) as discount_rate
from customer_shopping_behavior
group by Item_Purchased
order by discount_rate desc
limit 5;

select top 5*
from customer_shopping_behavior

--Q5 What is the revenue contribution of each age group?
select Age,
sum(Purchase_Amount_USD) as total_revenue
from customer_shopping_behavior
group by Age
order by total_revenue desc;
